LocalizerTranslations:
  reset_description:
    english: "Reset description text"
  mode_description:
    english: "Mode description text"
  addmode_description:
    english: "Add mode description text"
  deletemode_description:
    english: "Delete mode description text"
  introduce_description:
    english: "Introduce description text"
  fact_description:
    english: "Fact description text"
  clearfacts_description:
    english: "Clear facts description text"
  usage_description:
    english: "Usage description text"
  language_description:
    english: "Language description text"
  conversationtracker_description:
    english: "Conversation tracker description text"
  help_description:
    english: "Help description text"
  mode_set:
    english: "Mode {mode_name} set"
  mode_deleted:
    english: "Mode {mode_name} deleted"
  choose_mode:
    english: "Choose mode text"
  mode_added:
    english: "Mode {mode_name} added"
  inappropriate_mode:
    english: "Inappropriate mode text"
  choose_mode_to_delete:
    english: "Choose mode to delete text"
  introduction_added:
    english: "Introduction {user_handle} added"
  inappropriate_introduction:
    english: "Inappropriate introduction text"
  fact_added:
    english: "Fact {user_handle} added"
  inappropriate_fact:
    english: "Inappropriate fact text"
  facts_cleared:
    english: "Facts {user_handle} cleared"
  usage_text:
    english: "Usage {user_usage} text"
  language_set:
    english: "Language {language} set"
  language_set_error:
    english: "Language {language} set error"
  reset_done:
    english: "Reset done!"
  not_authenticated:
    english: "You are not authenticated to do this action"
  conversation_tracker_turned_on:
    english: "Conversation tracker turned on"
  conversation_tracker_turned_off:
    english: "Conversation tracker turned off"
  help_text:
    english: |
      <strong>Features ğŸŒŸ</strong>
      â€¢ <b>Create and use chat-bounded chat modes</b> by describing the agent and how you want it to act
      â€¢ <b>Introduce yourself to the model</b>
      â€¢ <b>Add facts about yourself or other people</b> that the model would later use
      â€¢ <b>Chat with the bot</b>:
        - Send it text ğŸ“
        - Send it pictures ğŸ“·
        - Send it voice messages ğŸ™
        - Receive back text ğŸ“©
        - Receive back pictures ğŸ–¼
      â€¢ <b>Flexible tracking of the AI resources usage</b> ğŸ“Š

      <strong>Bot commands ğŸ”§</strong>
      â€¢ <em>/reset</em> - Reset the dialogue history
      â€¢ <em>/mode [mode]</em> - Select chat mode from existing ones
      â€¢ <em>/addmode [mode] [description]</em> - Add new chat mode
      â€¢ <em>/deletemode [mode]</em> - delete existing chat mode from this chat
      â€¢ <em>/introduce [your introduction]</em> - Add fact about yourself
      â€¢ <em>/fact [@tg_handle] [fact]</em> - add fact about the person within the chat
      â€¢ <em>/clearfacts [@tg_handle]</em> - delete facts for given person
      â€¢ <em>/conversationtracker</em> - Turn on/off conversation tracker
      â€¢ <em>/usage</em> - Show usage limits for your user
      â€¢ <em>/language</em> - Set bot preferred language
      â€¢ <em>/help</em> - Show help
